import import_export from './import_export'
// import classes from './classes'
// import const_let from './const_let'
// import arrays from './arrays'
// import arrow_functions from './arrow_functions'
// import valores_padrao from './valores_padrao'
// import desestruturacao from './desestruturacao'
// import rest_spread from './rest_spread'
// import template_literals from './template_literals'
// import short_syntax from './short_syntax'
// import async_await from './async_await'